sudo: true

dist: trusty

language: python

python:
  - "3.6"

addons:
  postgresql: "9.5"

before_install:
  - psql -c "CREATE USER travis_admin WITH PASSWORD 'travis_admin'" -U postgres
  - psql -c "ALTER ROLE travis_admin SUPERUSER" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py test