sudo: true

language: python

python:
  - "3.6"

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10

before_install:
  - sudo -u postgres psql -c "CREATE USER travis WITH PASSWORD 'travis'"
  - sudo -u postgres psql -c "ALTER ROLE travis SUPERUSER"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test