sudo: true

language: python

python:
  - "3.6"

addons:
    postgresql: '10'
    apt:
        packages:
        - postgresql-10
        - postgresql-client-10

before_install:
  - psql -c "CREATE USER travis WITH PASSWORD 'travis'" -U postgres
  - psql -c "ALTER ROLE travis SUPERUSER" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py test