"""empty message

Revision ID: 27bdd230837d
Revises: cabc758645a1
Create Date: 2018-12-19 16:38:05.297347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bdd230837d'
down_revision = 'cabc758645a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'uuid')
    op.drop_column('User', 'registered_at')
    # ### end Alembic commands ###
