"""empty message

Revision ID: 62949e0d6a74
Revises: 
Create Date: 2018-12-18 18:31:01.372759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62949e0d6a74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
